services:
  - type: web
    name: blog-platform
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_project.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: blog_project.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString

databases:
  - name: blog-db
    databaseName: blogdb
    user: bloguser
